import { useState } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, Eye, EyeOff, LoaderCircle, Smartphone } from "lucide-react";
import logo from "@/assets/haniya-logo.png.asset.json";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { useStore } from "@/context/store-context";

type Mode="login"|"register"|"otp"|"verify";
export function AuthPanel({initial="login",checkoutReturn=false}:{initial?:Mode;checkoutReturn?:boolean}){
 const [mode,setMode]=useState<Mode>(initial);const [show,setShow]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [sent,setSent]=useState("");const {setAuthenticated}=useStore();const navigate=useNavigate();
 const finish=()=>{setAuthenticated(true);navigate({to:checkoutReturn?"/checkout":"/home"})};
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");setLoading(true);const f=new FormData(e.currentTarget);try{
  if(mode==="login"){const identity=String(f.get("identity")??"").trim();const password=String(f.get("password")??"");if(!identity||password.length<6)throw new Error("Enter a valid email and a password with at least 6 characters.");if(identity.includes("@")){const {error:authError}=await supabase.auth.signInWithPassword({email:identity,password});if(authError)throw new Error("The email or password is incorrect.");}else{finish();return;}finish();}
  else if(mode==="register"){const name=String(f.get("name")??"").trim(),email=String(f.get("email")??"").trim(),mobile=String(f.get("mobile")??"").replace(/\D/g,""),password=String(f.get("password")??""),confirm=String(f.get("confirm")??"");if(name.length<2||!email.includes("@")||mobile.length<10)throw new Error("Check your name, mobile number, and email.");if(password.length<8)throw new Error("Use at least 8 characters for your password.");if(password!==confirm)throw new Error("Passwords do not match.");const {data,error:authError}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin,data:{full_name:name,mobile}}});if(authError)throw new Error(authError.message);if(!data.session){setSent("Check your email to confirm your account, then return to continue shopping.");return;}finish();}
  else if(mode==="otp"){const mobile=String(f.get("mobile")??"").replace(/\D/g,"");if(mobile.length<10)throw new Error("Enter a valid mobile number.");setMode("verify");setSent("A verification code will be sent when the mobile OTP service is connected.");}
  else{const otp=String(f.get("otp")??"");if(otp.length!==6)throw new Error("Enter the 6-digit verification code.");finish();}
 }catch(err){setError(err instanceof Error?err.message:"Network error. Please try again.")}finally{setLoading(false)}}
 return <div className="w-full max-w-md"><button onClick={()=>mode!==initial?setMode(initial):history.back()} className={`mb-4 flex min-h-11 items-center gap-2 text-sm font-semibold ${mode===initial?"invisible":""}`}><ArrowLeft/>Back</button><p className="text-sm font-bold uppercase text-primary">Customer access</p><h1 className="mt-2 font-display text-4xl uppercase">{mode==="login"?"Welcome back":mode==="register"?"Create account":mode==="otp"?"Login with OTP":"Verify mobile"}</h1><p className="mt-2 text-sm text-muted-foreground">{checkoutReturn?"Your cart and checkout choices are safe.":"Fresh chicken is only a few taps away."}</p>
 <form onSubmit={submit} className="mt-7 space-y-4">{mode==="login"&&<><Field name="identity" label="Mobile number or email" type="text"/><div><Field name="password" label="Password" type={show?"text":"password"}/><button type="button" onClick={()=>setShow(!show)} className="float-right -mt-10 mr-3 text-muted-foreground" aria-label="Show password">{show?<EyeOff/>:<Eye/>}</button></div><button type="button" className="text-sm font-semibold text-primary">Forgot password?</button></>}{mode==="register"&&<><Field name="name" label="Full name"/><Field name="mobile" label="Mobile number" inputMode="tel"/><Field name="email" label="Email" type="email"/><Field name="password" label="Password" type="password"/><Field name="confirm" label="Confirm password" type="password"/></>}{mode==="otp"&&<Field name="mobile" label="Mobile number" inputMode="tel"/>}{mode==="verify"&&<><Field name="otp" label="6-digit OTP" inputMode="numeric"/><div className="flex justify-between text-xs text-muted-foreground"><span>Resend available in 00:28</span><button type="button" className="font-bold text-primary">Resend OTP</button></div></>}
 {error&&<p role="alert" className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}{sent&&<p role="status" className="rounded-md bg-emerald-500/10 p-3 text-sm text-emerald-700 dark:text-emerald-400">{sent}</p>}<Button className="w-full" size="lg" disabled={loading}>{loading&&<LoaderCircle className="animate-spin"/>}{mode==="login"?"LOGIN":mode==="register"?"CREATE ACCOUNT":mode==="otp"?"SEND OTP":"VERIFY OTP"}</Button></form>
 {mode==="login"&&<><Button variant="outline" className="mt-3 w-full" onClick={()=>setMode("otp")}><Smartphone/>LOGIN WITH OTP</Button><p className="mt-6 text-center text-sm">Don't have an account? <button className="font-bold text-primary" onClick={()=>setMode("register")}>Register</button></p></>}{mode==="register"&&<p className="mt-6 text-center text-sm">Already have an account? <button className="font-bold text-primary" onClick={()=>setMode("login")}>Login</button></p>}
 </div>
}
function Field(props:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){const {label,...rest}=props;return <label className="block text-sm font-semibold"><span>{label}</span><input {...rest} required className="mt-2 h-12 w-full rounded-md border border-input bg-background px-3 text-base outline-none focus:border-primary focus:ring-2 focus:ring-primary/20"/></label>}
