import { createFileRoute, Link } from "@tanstack/react-router";
import { Search, ArrowRight, ShieldCheck, Snowflake, Clock3 } from "lucide-react";
import hero from "@/assets/haniya-hero.jpg";
import { products, categories, offers } from "@/data/catalog";
import { ProductCard } from "@/components/store/product-card";
import { ShopShell } from "@/components/store/shop-shell";
import { Button } from "@/components/ui/button";
export const Route=createFileRoute("/home")({head:()=>({meta:[{title:"Fresh Chicken — Haniya Proteins"},{name:"description",content:"Shop fresh chicken breast, thighs, wings, legs, whole chicken and boneless cuts."},{property:"og:title",content:"Fresh Chicken — Haniya Proteins"},{property:"og:description",content:"Fresh chicken cuts, clear weights and simple ordering."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:HomePage});
function HomePage(){return <ShopShell><div className="mx-auto max-w-7xl px-4 py-4 lg:px-8"><Link to="/products" className="flex h-12 items-center gap-3 rounded-md border border-input bg-card px-4 text-muted-foreground"><Search className="size-5"/>Search chicken cuts...</Link><section className="relative mt-4 min-h-[330px] overflow-hidden rounded-lg md:min-h-[420px]"><img src={hero} width={1536} height={912} alt="Fresh chicken cuts ready for your kitchen" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-foreground/55"/><div className="relative flex min-h-[330px] max-w-xl flex-col justify-end p-6 text-primary-foreground md:min-h-[420px] md:p-12"><p className="text-xs font-extrabold uppercase">Cut fresh · Packed clean</p><h1 className="mt-3 font-display text-5xl uppercase leading-[1.05] md:text-7xl">Fresh Chicken,<br/>Made for Your Kitchen.</h1><p className="mt-3 max-w-md text-sm opacity-90 md:text-base">Choose your cut and weight. We keep the ordering simple.</p><Button asChild className="mt-6 w-fit" size="lg"><Link to="/products">Shop chicken <ArrowRight/></Link></Button></div></section>
<section className="mt-8"><div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-bold uppercase text-primary">Browse by cut</p><h2 className="font-display text-3xl uppercase">Chicken categories</h2></div><Link to="/products" className="text-sm font-bold text-primary">See all</Link></div><div className="-mx-4 flex gap-2 overflow-x-auto px-4 pb-2">{categories.map(c=><Link key={c} to="/products" search={{category:c}} className={`shrink-0 rounded-full border px-4 py-2 text-sm font-semibold ${c==="All"?"border-primary bg-primary text-primary-foreground":"border-border bg-card"}`}>{c}</Link>)}</div></section>
<section className="mt-9"><div className="mb-4"><p className="text-xs font-bold uppercase text-primary">Customer favourites</p><h2 className="font-display text-3xl uppercase">Popular chicken</h2></div><div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-4">{products.filter(p=>p.popular).map(p=><ProductCard key={p.id} product={p}/>)}</div></section>
<section className="mt-12 bg-foreground px-5 py-8 text-background md:px-8"><p className="text-xs font-bold uppercase text-primary">Current offers</p><h2 className="mt-1 font-display text-3xl uppercase">More value, same fresh cuts</h2><div className="mt-5 grid gap-px bg-background/20 md:grid-cols-2">{offers.map(o=><div key={o.id} className="bg-foreground p-5"><b>{o.title}</b><p className="mt-1 text-sm opacity-70">{o.detail}</p><span className="mt-4 inline-block border border-background/30 px-3 py-1 font-mono text-xs">{o.code}</span></div>)}</div></section>
<section className="grid gap-8 border-b border-border py-12 md:grid-cols-2"><div><p className="text-xs font-bold uppercase text-primary">Our standard</p><h2 className="mt-2 font-display text-4xl uppercase">Fresh chicken. <span lang="ar">حلال</span></h2><p className="mt-4 max-w-lg text-sm leading-6 text-muted-foreground">Carefully presented chicken cuts for everyday kitchens. Specific sourcing and certification details will be added once provided by the business.</p></div><div className="grid grid-cols-3 gap-3">{[[Snowflake,"Fresh cuts"],[ShieldCheck,"Clean handling"],[Clock3,"Practical ordering"]].map(([I,t])=>{const Icon=I as typeof Search;return <div key={String(t)} className="border-l-2 border-primary p-3"><Icon className="mb-4 text-primary"/><b className="text-sm">{String(t)}</b></div>})}</div></section>
<section className="grid gap-8 py-12 md:grid-cols-2"><div><p className="text-xs font-bold uppercase text-primary">About</p><h2 className="mt-2 font-display text-3xl uppercase">Haniya Proteins</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Business story and sourcing information will appear here when supplied by Haniya Proteins.</p></div><div><p className="text-xs font-bold uppercase text-primary">Contact</p><h2 className="mt-2 font-display text-3xl uppercase">We're here to help</h2><p className="mt-3 text-sm text-muted-foreground">Phone, email, address and opening hours will be available here once confirmed.</p></div></section></div><footer className="border-t border-border px-4 py-10 text-sm"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 md:flex-row"><div><b className="font-display text-xl uppercase">Haniya Proteins</b><p className="text-muted-foreground">Fresh Chicken, Made for Your Kitchen.</p></div><div className="flex flex-wrap gap-5"><Link to="/products">Products</Link><Link to="/orders">Orders</Link><Link to="/profile">Profile</Link></div></div></footer></ShopShell>}
